# Permalinks
permalink:            /:categories/:title

# Setup
title:                Tobias Løfgren's Blog
description:          "This is the personal blog of me, Tobias Løfgren, where I write about the interesting programming projects I do."
paginate:             10
baseurl:              ""
url:                  "https://tobloef.com"
excerpt_separator:    <!--more-->
timezone:             Europe/Copenhagen
disqus_shortname:     "tobloef"
google_analytics:     "UA-73558830-1"

# Assets
sass:
  sass_dir:           _sass
  style:              :compressed

# Build settings
markdown:             kramdown
strict_front_matter:  true

# Defaults
defaults:
  -
    scope:
      type:           "posts"
    values:
      #permalink:       /blog/:categories/:title
      comments:        true
      author:         "Tobias Løfgren"

# About
author:
  name:               Tobias Løfgren
  url:                http://tobloef.com
  email:              tobloef@gmail.com
  github:             https://github.com/tobloef

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from